version: "2.0"

services:
  skill_load_unload:
    image: "jupiterbak2002/skill_load_unload:latest"
    restart: always
    pull: true
    container_name: skill_load_unload
    hostname: skill_load_unload
    # environment:
    #  - DNS_ADDRESS="8.8.8.8" # TODO: Please change the DNS default address if needed, otherwise remove this variable
    ports:
      - "4842:4842"
    networks: 
      - backend
  skill_insert:
    image: "jupiterbak2002/skill_insert:latest"
    restart: always
    pull: true
    container_name: skill_insert
    hostname: skill_insert
    # environment:
    #   - DNS_ADDRESS="8.8.8.8" # TODO: Please change the DNS default address if needed, otherwise remove this variable
    ports:
      - "4840:4840"
    networks: 
      - backend
  skill_add:
    image: "jupiterbak2002/skill_add:latest"
    restart: always
    pull: true
    container_name: skill_add
    hostname: skill_add
    # environment:
    #   - DNS_ADDRESS="8.8.8.8" # TODO: Please change the DNS default address if needed, otherwise remove this variable
    ports:
      - "4843:4843"
    networks: 
      - backend  
  skill_monitoring:
    image: "jupiterbak2002/skill_monitoring:latest"
    restart: always
    pull: true
    container_name: skill_monitoring
    hostname: skill_monitoring
    # environment:
    #   - DNS_ADDRESS="8.8.8.8" # TODO: Please change the DNS default address if needed, otherwise remove this variable
    ports:
      - "8080:8080"
    networks:
      backend:  
  skill_invocation_client:
    image: "jupiterbak2002/skill_invocation_client:latest"
    restart: always
    pull: true
    container_name: skill_invocation_client
    hostname: skill_invocation_client
    environment:
      - OPCUA_BACKEND_URL=http://skill_monitoring:8080/
      - DNS_ADDRESS="8.8.8.8" # TODO: Please change the DNS default address if needed, otherwise remove this variable
    ports:
      - "7400:7400"
    depends_on:
      - skill_monitoring
    links:
      - skill_monitoring
    networks: 
      - backend
    volumes:
      -  skill_invocation_client-shapes:/usr/src/app/shapes
      -  skill_invocation_client-sequences:/usr/src/app/.skillInvocationClient

networks:
  backend:
    # ipam:
    #   config:
    #     - subnet: 172.31.0.0/16

volumes:
  skill_invocation_client-shapes:
    driver: local
    driver_opts:
      source: /tmp/data
  skill_invocation_client-sequences:
    driver: local
    driver_opts:
      source: /tmp/data
  # driver: local
  # driver_opts:
  #   type: none
  #   device: ${WEB_APP_PATH}
  #   o: bind