version: "2.0"

services:
  skill_monitoring:
    image: "jupiterbak2002/skill_monitoring"
    restart: always
    container_name: skill_monitoring
    ports:
      - "8080:8080"
    networks: 
      - backend      
  
  skill_invocation_client:
    image: "jupiterbak2002/skill_invocation_client"
    restart: always
    container_name: skill_invocation_client
    environment:
      - OPCUA_BACKEND_URL=http://skill_monitoring:8080/
    ports:
      - "7400:7400"
    depends_on:
      - skill_monitoring
    links:
      - skill_monitoring
    networks: 
      - backend
    volumes:
      -  skill_invocation_client-shapes:/usr/src/app/shapes
      -  skill_invocation_client-sequences:/usr/src/app/.skillInvocationClient

networks:
  backend:

volumes:
  skill_invocation_client-shapes:
  skill_invocation_client-sequences:
