uiPort: 7400
services:
  opcuaclient: False
  opcua_dicovery:
    discoveryServerEndpointUrl: 'opc.tcp://localhost:48400'
    connection_options:
      applicationName: "SIC Discovery server client"
      endpoint_must_exist: False
      keepSessionAlive: True
      requestedSessionTimeout: 60000
      connectionStrategy: infinite_connectivity_strategy
