swagger: "2.0"
info:
  description: "Sample API for the Siemens Skill Invocation Client. Using this API, a machine or module can register itself to the tool and also browse all avialable skills"
  version: "1.0.0"
  title: "Skill Invocation Client API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "jupiter.bakakeu@faps.fau.de"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
basePath: "/v1"
tags:
- name: "skill invocation client"
  description: "Access to the Skill Invocation Client"
schemes:
- "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /skills:
    x-swagger-router-controller: "skill_router"
    get:
      summary: "Get all saved skill definitions"
      description: ""
      operationId: "listSkills"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Skill"
    post:
      summary: "Register a new module"
      description: ""
      operationId: "registerModule"
      parameters:
      - in: "body"
        name: "module"
        description: "Module object and OPC UA Server description that needs to be browsed."
        required: true
        schema:
          $ref: "#/definitions/Module"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Skill"
    put:
      summary: "Update the skills of a module"
      description: ""
      operationId: "updateModule"
      parameters:
      - in: "body"
        name: "module"
        description: "Module object and OPC UA Server description that needs to be updated."
        required: true
        schema:
          $ref: "#/definitions/Module"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Skill"
  
  /skills/{moduleName}:
    x-swagger-router-controller: "skill_router"
    get:
      summary: "Get all the skills belonging to a module."
      description: ""
      operationId: "getSkillsByModule"
      parameters:
        - name: "moduleName"
          in: "path"
          required: true
          description: "The name of module to search for."
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Skill"
        "400":
          description: "Invalid status value"
    delete:
      summary: "Delete a skill from the repository"
      description: ""
      operationId: "deleteModule"
      parameters:
        - name: "moduleName"
          in: "path"
          required: true
          description: "The name of the module to remove"
          type: "string"
      responses:
        "200":
            description: "OK."
        "405":
          description: "Invalid input"
  
definitions:
  Module:
    type: "object"
    required:
    - "name"
    - "ip"
    - "port"
    properties:
      name:
        type: "string"
        example: "InsertSkill"
      ip:
        type: "string"
        example: "192.168.0.1"
      port:
        type: "integer"
        format: "int32"
        example: 4840
  Skill:
    type: "object"
    required:
    - "name"
    - "module_name"
    - "ip"
    - "port"
    properties:
      name:
        type: "string"
        example: "InsertSkill"
      module_name:
        type: "string"
        example: "AssemblyModule 1"
      ip:
        type: "string"
        example: "192.168.0.1"
      port:
        type: "integer"
        format: "int32"
        example: 4840
      nodeId:
        type: "string"
        example: "ns=4;i=7001"
      version:
        type: "string"
        example: "V1"
